config/routes.rb
Rails.application.routes.draw do
  resources :usr_buyer_payment_methods
  get 'usr_buyer/index'

  get 'usr_buyer/new'

  post 'usr_buyer/create'

  get 'usr_buyer/edit'

  post 'usr_buyer/update'

  post 'usr_buyer/destroy'

  resources :usr_vender

  root 'usr_vender#index'
  # get 'usr/index'
  #
  # get 'usr/register'

  #devise_for :usr_contacts


  devise_for :usr_contacts, :controllers => { registrations: 'registrations' }
  #devise_for :contacts
  # devise_scope :contacts do
  #   #@request.env["devise.mapping"] = Devise.mappings[:users]
  #   match '/users/index', to: 'devise/sessions#new', via: :get
  #   get 'users/index' => "users"
  #   get 'users/register'
  # end

  devise_scope :usr_contacts do
    get '/usr/index' => "usr#index"
    get '/usr/register' => "usr#register"
  end

  #resourceful route for usr_roles controller
  resources :usr_roles

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/usr_buyer.rb
class UsrBuyer < ApplicationRecord
  belongs_to :usr_contact
  has_many :usr_buyer_billing_adderesses
  has_many :usr_buyer_delivery_adderesses
  has_many :usr_buyer_payment_methods

  mount_uploader :user_image, UsrContactUploader

end

app/models/usr_contact.rb
class
UsrContact < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :image, UsrContactUploader
  has_one :usr_buyer
  #creating many to many relationship with usr_roles table
  has_many :usr_contact_roles
  has_many :usr_roles, through: :usr_contact_roles

  # validations for sing in
  validates :name, :presence => true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  validate :password_complexity
  def password_complexity
    if password.present? and not password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)./)
      errors.add :password, "must include at least one lowercase letter, one uppercase letter, and one digit"
    end
  end
  has_and_belongs_to_many :usr_vender_properties

end

app/models/usr_contact_role.rb
class UsrContactRole < ApplicationRecord

  #creating many to many relationship with usr_user table and usr_role table
  #this is intermediate table
  belongs_to :usr_contact
  belongs_to :usr_role

end

app/models/usr_contact_vender.rb
class UsrContactVender < ApplicationRecord
  belongs_to :UsrContact
  belongs_to :UsrVenderProperty
end

app/models/usr_permission.rb
class UsrPermission < ApplicationRecord

  #creating many to many relationship with usr_role table
  has_many :usr_role_permissions
  has_many :usr_roles, through: :usr_role_permissions

end

app/models/usr_role.rb
class UsrRole < ApplicationRecord

  #creating many to many relationship with usr_permission table
  has_many :usr_role_permissions
  has_many :usr_permissions, through: :usr_role_permissions

  #creating many to many relationship with usr_user table
  has_many :usr_contact_roles
  has_many :usr_contacts, through: :usr_contact_roles

  #role_name validation
  validates :role_name, :description, presence: true

end

app/models/usr_role_permission.rb
class UsrRolePermission < ApplicationRecord

  #creating many to many relationship with usr_role table and usr_permission table
  #this is intermediate table
  belongs_to :usr_role
  belongs_to :usr_permission

end

app/models/usr_vender_property.rb
class UsrVenderProperty < ApplicationRecord
  has_and_belongs_to_many :usr_contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  private
  def after_sign_in_path_for(resource)
    root_path
  end



  # private
  # def after_sign_in_path_for(resource)
  #  #if session[:userType].nil?
  #
  #  # if Rails.application.config.session_store key:'userType' == "sellert"
  #   #if cookies[:userType] == "seller"
  #   if session[:userType]=='sellerZ'
  #     usr_register_path
  #   else
  #     root_path
  #   end
  # end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:usr_contact).permit(:name, :mobile, :email, :password, :password_confirmation, :image)
  end

  def account_update_params
    params.require(:usr_contact).permit(:name, :mobile, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/usr_buyer_controller.rb
class UsrBuyerController < ApplicationController
  def index
    @currentuserid = current_usr_contact.id
    @buyer_details = UsrBuyer.find(id= @currentuserid)
  end

  def new
    @buyer = UsrBuyer.new
    @usr_buyer_payment_method = UsrBuyerPaymentMethod.new
  end

  def create
    @buyer = UsrBuyer.new(buyer_params)
    @buyer.usr_contact_id = @currentuserid
    @usr_buyer_payment_method = UsrBuyerPaymentMethod.new(usr_buyer_payment_method_params)
    if @buyer.save()
      redirect_to root_path, notice: 'Buyer details successfully updated' and return
    else
      redirect to root_path, notice: 'Buyer details could not be saved successfully' and return
    end

    if @usr_buyer_payment_method.save
      redirect_to root_path, notice: 'Usr buyer payment method was successfully created.' and return
    else
      redirect_to root_path, notice: 'Usr buyer payment method was not successfully created.' and return
    end

  end

  def edit
    @buyer = UsrBuyer.find(usr_contact_id = @currentuserid)
  end

  def update
    @buyer = UsrBuyer.find(usr_contact_id = @currentuserid)
    if @buyer.update_attributes(buyer_params)
      redirect_to root_path
    else
      redirect_to root_path
    end


  end

  def destroy

  end

  private
  def buyer_params
    params.require(:usr_buyer).permit(:user_image, :gender, :first_name, :last_name, :contact_number, :dob, :anniversary )
  end
  def usr_buyer_payment_method_params
    params.require(:usr_buyer_payment_method).permit(:card_name, :card_number, :cvv, :expiry_date)
  end
end

app/controllers/usr_controller.rb
class UsrController < ApplicationController
  def index
    @cotacts = UsrContact.all # get all registerd contacts
  end

  def register
  end
end

app/controllers/usr_permissions_controller.rb
class UsrPermissionsController < ApplicationController

  def index
  end

end

app/controllers/usr_registrations_controller.rb
class UsrRegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:usr_contact).permit(:name, :mobile, :email, :password, :password_confirmation, :image)
  end

  def account_update_params
    params.require(:usr_contact).permit(:name, :mobile, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/usr_roles_controller.rb
class UsrRolesController < ApplicationController

  def index
    @roles = UsrRole.all #show all users
  end

  def new
    @role = UsrRole.new
    @all_permissions = UsrPermission.all
    @role_permissions = @role.usr_role_permissions.build
  end

  def create
    @role = UsrRole.new(role_params)
    params[:usr_permissions][:id].each do |permission|
      if !permission.empty?
        @role.usr_role_permissions.build(:usr_permission_id => permission, :value => '######')
      end
    end
    if @role.save
      @test = UsrRolePermission.new()
      redirect_to usr_roles_path
    else
      render 'new'
    end
  end

  def show
    @role = UsrRole.find(params[:id])
    @permissions = @role.usr_permissions
  end

  private
  def role_params
    params.require(:usr_role).permit(:role_name, :description)
  end

end

app/controllers/usr_vender_controller.rb
class UsrVenderController < ApplicationController

  def index
  end

  def new
    @vender_property = UsrVenderProperty.new
  end

  def create
    @vender_property = UsrVenderProperty.new(vender_property_params)
    @currentuser = current_usr_contact
    @user_contct_vender = UsrContactVender.new()


    if @vender_property.save
      @vender_property_last = UsrVenderProperty.last.id
      @user_contct_vender.usr_contacts_id =  @currentuser.id
      @user_contct_vender.usr_vender_properties_id = @vender_property_last

      if @user_contct_vender.save
        redirect_to root_path
      end

    else
      render 'new'
    end
  end

  private
  def vender_property_params
    params.require(:post).permit(:specifiedArea, :mobile)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/usr_buyer_helper.rb
module UsrBuyerHelper
end

app/helpers/usr_helper.rb
module UsrHelper
end

app/helpers/usr_permissions_helper.rb
module UsrPermissionsHelper
end

app/helpers/usr_roles_helper.rb
module UsrRolesHelper
end

app/helpers/usr_vender_helper.rb
module UsrVenderHelper
end

app/views/usr_buyer/_form.html.erb
<style>
  .kv-avatar .file-preview-frame,.kv-avatar .file-preview-frame:hover {
    margin: 0;
    padding: 0;
    border: none;
    box-shadow: none;
    text-align: center;
  }
  .kv-avatar .file-input {
    display: table-cell;
    max-width: 220px;
  }
</style>



<div class="kv-avatar center-block" style="width:200px">
  Image<%= f.file_field :user_image, class: "file-loading", id:"avatar-2", name:"avatar-2" %>
</div>
<div id="kv-avatar-errors-2" class="center-block" style="width:800px;display:none"></div>

<div class="form-group">
  First Name<%= f.text_field :first_name, class: "form-control" %>
</div>
<div class="form-group">
  Last Name<%= f.text_field :last_name, class: "form-control" %>
</div>
<div class="form-group">
  Contact Number<%= f.text_field :contact_number, class: "form-control" %>
</div>
<div class="form-group">
  Date of Birth<%= f.text_field :dob, id: "datepicker", class: "form-control" %>
</div>
<div class="form-group">
  Anniversary Date<%= f.text_field :anniversary, id: "datepicker1", class: "form-control" %>
</div>





<script>
    var btnCust = '<button type="button" class="btn btn-default" title="Add picture tags" ' +
        'onclick="alert(\'Call your custom code here.\')">' +
        '<i class="glyphicon glyphicon-tag"></i>' +
        '</button>';
    $("#avatar-2").fileinput({
        overwriteInitial: true,
        maxFileSize: 1500,
        showClose: false,
        showCaption: false,
        showBrowse: false,
        browseOnZoneClick: true,
        removeLabel: '',
        removeIcon: '<i class="glyphicon glyphicon-remove"></i>',
        removeTitle: 'Cancel or reset changes',
        elErrorContainer: '#kv-avatar-errors-2',
        msgErrorClass: 'alert alert-block alert-danger',
        defaultPreviewContent: '<img src="/uploads/default_avatar_male.jpg" alt="Your Avatar" style="width:160px"><h6 class="text-muted">Click to select</h6>',
        layoutTemplates: {main2: '{preview} ' +  btnCust + ' {remove} {browse}'},
        allowedFileExtensions: ["jpg", "png", "gif"]
    });
</script>

app/views/usr_buyer/create.html.erb
<h1>Buyers#create</h1>
<p>Find me in app/views/buyers/create.html.erb</p>

app/views/usr_buyer/destroy.html.erb
<h1>Buyers#destroy</h1>
<p>Find me in app/views/buyers/destroy.html.erb</p>

app/views/usr_buyer/edit.html.erb
<div class = "well">
  <%= form_for @buyer, url: usr_buyer_update_path, :method => :POST do |e| %>
      <%= render partial: "usr_buyer/form", locals: {:f => e} %>

      <%= e.submit "Save", class: "btn-block btn-primary" %>
  <% end %>
</div>

app/views/usr_buyer/new.html.erb
<div class = "well">
  <h3>Register as a Buyer</h3>
  <%= form_for @buyer, url: {action: "create"} do |e| %>
      <%= render partial: "usr_buyer/form", locals: {:f => e} %>

      <%= e.submit "Save", class: "btn-block btn-primary" %>
  <% end %>
</div>

app/views/usr_buyer/update.html.erb
<h1>Buyer#update</h1>
<p>Find me in app/views/buyer/update.html.erb</p>

app/views/usr_permissions/index.html.erb
<h1>Permissions#index</h1>
<p>Find me in app/views/permissions/index.html.erb</p>

app/views/usr_roles/home.html.erb
<div class="container">
<div class="form">
  <h1>This is Home Page</h1><br>
</div>
</div>

app/views/usr_roles/index.html.erb
<div class="container" >
  <h1>All Roles</h1>
  <hr>
  <% @roles.each do |role|%>
      <div>
        <h4><%= role.id %> . <%= link_to role.role_name, usr_role_path(role) %></h4>
      </div>
      <div>
        <!--<p><%= role.description %></p>-->
      </div>
  <% end %>
</div>

app/views/usr_roles/new.html.erb
<div class="form">
  <h1>Add new Role</h1><br>

  <hr>

  <%= form_for @role, url usr_roles_create_path do |m| %>

      <%= m.label(:role_name) %>
      <%= m.text_field(:role_name, {:placeholder => "Enter role name",:class => 'form-control'})%><br>

      <%= m.label(:description)%>
      <%= m.text_area(:description, {:placeholder => "Enter small description",:class => 'form-control'}) %><br>

      <%= fields_for(@role_permissions) do |rp| %>
          <div>
            <%= rp.label(:choose_permissions)%><br/>
            <%= collection_select(:usr_permissions, :id, @all_permissions, :id, :permission_name, {}, {:multiple => true,:class => 'form-control'})%>
          </div>
      <% end %>




      <br/>

      <%= m.submit "Create Role", class: "btn btn-success" %>

  <% end %>


</div>

app/views/usr_roles/show.html.erb
<div class="container" >
<hr>
<h2>Permissions</h2>
<hr>
<div >
  <% @permissions.each do |permission| %>

        <h4>
          <%= permission.permission_name %> :
        </h4>

  <% end %>
</div>
</div>