config/routes.rb
Rails.application.routes.draw do
  resources :usr_buyer_payment_methods
  get 'usr_buyer/index'

  get 'usr_buyer/new'

  post 'usr_buyer/create'

  get 'usr_buyer/edit'

  post 'usr_buyer/update'

  post 'usr_buyer/destroy'

  resources :usr_vender

  root 'usr_vender#index'
  # get 'usr/index'
  #
  # get 'usr/register'

  #devise_for :usr_contacts


  devise_for :usr_contacts, :controllers => { registrations: 'registrations' }
  #devise_for :contacts
  # devise_scope :contacts do
  #   #@request.env["devise.mapping"] = Devise.mappings[:users]
  #   match '/users/index', to: 'devise/sessions#new', via: :get
  #   get 'users/index' => "users"
  #   get 'users/register'
  # end

  devise_scope :usr_contacts do
    get '/usr/index' => "usr#index"
    get '/usr/register' => "usr#register"
  end

  #resourceful route for usr_roles controller
  resources :usr_roles

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/usr_buyer.rb
class UsrBuyer < ApplicationRecord
  belongs_to :usr_contact
  has_many :usr_buyer_billing_adderesses
  has_many :usr_buyer_delivery_adderesses
  has_many :usr_buyer_payment_methods

  mount_uploader :user_image, UsrContactUploader

end

app/models/usr_contact.rb
class
UsrContact < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :image, UsrContactUploader
  has_one :usr_buyer
  #creating many to many relationship with usr_roles table
  has_many :usr_contact_roles
  has_many :usr_roles, through: :usr_contact_roles

  # validations for sing in
  validates :name, :presence => true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  validate :password_complexity
  def password_complexity
    if password.present? and not password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)./)
      errors.add :password, "must include at least one lowercase letter, one uppercase letter, and one digit"
    end
  end
  has_and_belongs_to_many :usr_vender_properties

end

app/models/usr_contact_role.rb
class UsrContactRole < ApplicationRecord

  #creating many to many relationship with usr_user table and usr_role table
  #this is intermediate table
  belongs_to :usr_contact
  belongs_to :usr_role

end

app/models/usr_contact_vender.rb
class UsrContactVender < ApplicationRecord
  belongs_to :UsrContact
  belongs_to :UsrVenderProperty
end

app/models/usr_permission.rb
class UsrPermission < ApplicationRecord

  #creating many to many relationship with usr_role table
  has_many :usr_role_permissions
  has_many :usr_roles, through: :usr_role_permissions

end

app/models/usr_role.rb
class UsrRole < ApplicationRecord

  #creating many to many relationship with usr_permission table
  has_many :usr_role_permissions
  has_many :usr_permissions, through: :usr_role_permissions

  #creating many to many relationship with usr_user table
  has_many :usr_contact_roles
  has_many :usr_contacts, through: :usr_contact_roles

  #role_name validation
  validates :role_name, :description, presence: true

end

app/models/usr_role_permission.rb
class UsrRolePermission < ApplicationRecord

  #creating many to many relationship with usr_role table and usr_permission table
  #this is intermediate table
  belongs_to :usr_role
  belongs_to :usr_permission

end

app/models/usr_vender_property.rb
class UsrVenderProperty < ApplicationRecord
  has_and_belongs_to_many :usr_contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  private
  def after_sign_in_path_for(resource)
    root_path
  end



  # private
  # def after_sign_in_path_for(resource)
  #  #if session[:userType].nil?
  #
  #  # if Rails.application.config.session_store key:'userType' == "sellert"
  #   #if cookies[:userType] == "seller"
  #   if session[:userType]=='sellerZ'
  #     usr_register_path
  #   else
  #     root_path
  #   end
  # end
end

app/controllers/usr_buyer_controller.rb
class UsrBuyerController < ApplicationController
  def index
    @currentuserid = current_usr_contact.id
    @buyer_details = UsrBuyer.find(id= @currentuserid)
  end

  def new
    @buyer = UsrBuyer.new
    @usr_buyer_payment_method = UsrBuyerPaymentMethod.new
  end

  def create
    @buyer = UsrBuyer.new(buyer_params)
    @buyer.usr_contact_id = @currentuserid
    @usr_buyer_payment_method = UsrBuyerPaymentMethod.new(usr_buyer_payment_method_params)
    if @buyer.save()
      redirect_to root_path, notice: 'Buyer details successfully updated' and return
    else
      redirect to root_path, notice: 'Buyer details could not be saved successfully' and return
    end

    if @usr_buyer_payment_method.save
      redirect_to root_path, notice: 'Usr buyer payment method was successfully created.' and return
    else
      redirect_to root_path, notice: 'Usr buyer payment method was not successfully created.' and return
    end

  end

  def edit
    @buyer = UsrBuyer.find(usr_contact_id = @currentuserid)
  end

  def update
    @buyer = UsrBuyer.find(usr_contact_id = @currentuserid)
    if @buyer.update_attributes(buyer_params)
      redirect_to root_path
    else
      redirect_to root_path
    end


  end

  def destroy

  end

  private
  def buyer_params
    params.require(:usr_buyer).permit(:user_image, :gender, :first_name, :last_name, :contact_number, :dob, :anniversary )
  end
  def usr_buyer_payment_method_params
    params.require(:usr_buyer_payment_method).permit(:card_name, :card_number, :cvv, :expiry_date)
  end
end

app/controllers/usr_controller.rb
class UsrController < ApplicationController
  def index
    @cotacts = UsrContact.all # get all registerd contacts
  end

  def register
  end
end

app/controllers/usr_roles_controller.rb
class UsrRolesController < ApplicationController

  def index
    @roles = UsrRole.all #show all users
  end

  def new
    @role = UsrRole.new
    @all_permissions = UsrPermission.all
    @role_permissions = @role.usr_role_permissions.build
  end

  def create
    @role = UsrRole.new(role_params)
    params[:usr_permissions][:id].each do |permission|
      if !permission.empty?
        @role.usr_role_permissions.build(:usr_permission_id => permission, :value => '######')
      end
    end
    if @role.save
      @test = UsrRolePermission.new()
      redirect_to usr_roles_path
    else
      render 'new'
    end
  end

  def show
    @role = UsrRole.find(params[:id])
    @permissions = @role.usr_permissions
  end

  private
  def role_params
    params.require(:usr_role).permit(:role_name, :description)
  end

end

app/controllers/usr_vender_controller.rb
class UsrVenderController < ApplicationController

  def index
  end

  def new
    @vender_property = UsrVenderProperty.new
  end

  def create
    @vender_property = UsrVenderProperty.new(vender_property_params)
    @currentuser = current_usr_contact
    @user_contct_vender = UsrContactVender.new()


    if @vender_property.save
      @vender_property_last = UsrVenderProperty.last.id
      @user_contct_vender.usr_contacts_id =  @currentuser.id
      @user_contct_vender.usr_vender_properties_id = @vender_property_last

      if @user_contct_vender.save
        redirect_to root_path
      end

    else
      render 'new'
    end
  end

  private
  def vender_property_params
    params.require(:post).permit(:specifiedArea, :mobile)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/usr_buyer_helper.rb
module UsrBuyerHelper
end

app/helpers/usr_helper.rb
module UsrHelper
end

app/helpers/usr_permissions_helper.rb
module UsrPermissionsHelper
end

app/helpers/usr_roles_helper.rb
module UsrRolesHelper
end

app/helpers/usr_vender_helper.rb
module UsrVenderHelper
end

app/views/buyer/new.html.erb
<div class = "well">
  <%= form_for @buyer, url: {action: "create"} do |e| %>
      <%= render partial: "buyer/form" , locals: {:f => e} %>

      <%= e.submit "Save", class: "btn-block btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smartmall</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js' %>

  <%= javascript_include_tag 'https://code.jquery.com/ui/1.12.1/jquery-ui.js' %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js' %>

  <%= stylesheet_link_tag    'https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css'%>

  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


  <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->
  <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">-->
  <script>
    $( function() {
      $( "#datepicker" ).datepicker();
    } );
    $( function() {
      $( "#datepicker1" ).datepicker();
    } );
  </script>

</head>

<body>
<nav class="navbar navbar-inverse ">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Smart Mall</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
        <li><%= link_to "Register Items"%></li>
        <li><%= link_to "All Items" %></li>
        <li><%= link_to "Sell", new_usr_vender_path %></li>
        <li><%= link_to "Buyer", usr_buyer_new_path %></li>

      </ul>

      <ul class="nav navbar-nav">
        <li ><%= link_to "All roles", usr_roles_path %></li>
      </ul>


      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Login", new_usr_contact_session_path , :class=>'glyphicon glyphicon-log-in'%></li>
        <li><%= link_to "Sign up", new_usr_contact_registration_path , :class=>'glyphicon glyphicon-user'%></li>
        <li><%= link_to "Sign out", destroy_usr_contact_session_path, method: :delete%></li>
        <li><%= link_to "Create Role", new_usr_role_path %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>
</body>
</html>